### ISSUE TITLE
NFT not showing when i connect wallet 

### ISSUE THREAD

**Issue by omaritto99** [gemworks/gem-farm-ui#1]
Hey , 

please when i connect the wallet to the minting page i can't see the NFTs on the website , 
with a message saying ' There are no NFTs on your vault.' 
i have tried to chnage the RPC to : https://api.devnet.solana.com
instead of : https://wispy-icy-glitter.solana-devnet.quiknode.pro/8e987a31160f3b52d01f5706b34a86698164e30b/

but still the same problem  

thanks for help

**Comment by daddydonke** [comment]
Same issue.  Reviewing useWalletNFTs.tsx for issues.

**Comment by JerryIT1** [comment]
Solved: Go to file useGemFarmStaking.ts and replace the candy machine ID.

**Comment by daddydonke** [comment]
useGemFarmStaking.ts

Your Candy Machine needs to be used to replace: '9bAVeEj62aBZVspYu5iEo2GSLRzFwLYgEsX5CoeCHN2n'

**Comment by omaritto99** [comment]
Working fine now , thanks guys

**Comment by eliagoris** [comment]
Yoo I forgot to mention that.

> useGemFarmStaking.ts
> 
> Your Candy Machine needs to be used to replace: '9bAVeEj62aBZVspYu5iEo2GSLRzFwLYgEsX5CoeCHN2n'

Yep I forgot to mention that on the readme.

Bad thing is through the UI would need another input

**Comment by eliagoris** [comment]
Last commit (https://github.com/gemworks/gem-farm-ui/commit/8e9f27488e247e21308516df3b032393a0647d7d) will fetch all NFTs regardless of creator address. Later I can see the best way to add a filter to it
