### ISSUE TITLE
How to filter nft?

### ISSUE THREAD

**Issue by firdisml** [gemworks/gem-farm-ui#10]
hey there is there any way to filter only nft from certain smart contract/creator?

**Comment by eliagoris** [comment]
Added this on https://github.com/gemworks/gem-farm-ui/commit/83a387352a1583f0f4c45dd7b60d61cc08bbbf35

Only have to add an array of creator addresses to https://github.com/gemworks/gem-farm-ui/blob/main/hooks/useWalletNFTs.tsx#L33
