### ISSUE TITLE
NEXT_PUBLIC_GA_ID Meaning

### ISSUE THREAD

**Issue by MarioProjects** [gemworks/gem-farm-ui#11]
Heyo, thanks for the Frontend! Looks great.

What is the env `NEXT_PUBLIC_GA_ID` used for?

**Comment by MarioProjects** [comment]
Okay, after a bit of research I think stands for 'Google Analytics', could you give some brief doc?

**Comment by reyzaraf** [comment]
You can ignore / comment / delete next_public_ga_id. It's not effect to the staking function.

**Comment by eliagoris** [comment]
`NEXT_PUBLIC_GA_ID `  Is an optional Google Analytics (Universal Analytics) tag for measuring user access to your app. Check out https://support.google.com/analytics/answer/10269537?hl=en on how to set up.
