### ISSUE TITLE
Adding NFTs to old Vault

### ISSUE THREAD

**Issue by MarioProjects** [gemworks/gem-farm-ui#12]
When I want to add NFTs I have to unstake first, add to the vault and then stake again. That causes paying fees for unstaking and re-stakign again and I don't know if variable staking rewards based on staked time too... Could be changed?

**Comment by eliagoris** [comment]
This is more feedback for the [gem-farm repo](https://github.com/gemworks/gem-farm). Can't work on that through the UI
