### ISSUE TITLE
error when deploying with netlify

### ISSUE THREAD

**Issue by shockValue666** [gemworks/gem-farm-ui#13]
when i try to deploy with netlify i get the following errors: 
"A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred",

"TypeError: Failed to construct 'URL': Invalid URL"

The deployment is successful but when i visit the page, nothing shows up and in the console, those 2 errors appear.
These errors appear both on my "changed" version of the repo and the original that i tried to fork and deploy

**Comment by eliagoris** [comment]
@shockValue666 This is likely because there aren't environment variables set on your Netlify config. Check [.env.template](https://github.com/gemworks/gem-farm-ui/blob/main/.env.template) for the required variables.

**Comment by shockValue666** [comment]
yeah this was it! thnx for your answer

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
