### ISSUE TITLE
Migrate from deprecated "@metaplex/js" to new Metaplex SDK - "@metaplex-foundation/js"

### ISSUE THREAD

**Issue by kubaplata** [gemworks/gem-farm-ui#15]
Gem Farm UI is still using old Metaplex SDK - "@metaplex/js". Last library update was 7 months ago, and since then new SDK has been published - "@metaplex-foundation/js". 

Using deprecated library can cause many problems in the future, including potential incompatibility. I think it's a good idea to migrate to the new SDK, to avoid these issues.

**Comment by kubaplata** [comment]
#16

**Comment by eliagoris** [comment]
Reopened because the PR https://github.com/gemworks/gem-farm-ui/pull/16 is not working (check PR for info), and this migration seems useful =)

**Comment by eliagoris** [comment]
This is an excellent example of an app using `@metaplex-foundation/js`: https://github.com/mentalabsio/solana-web-app.

If anyone would like to contribute, can use some code from there =)

**Comment by kubaplata** [comment]
#18
