### ISSUE TITLE
No NFTs showing

### ISSUE THREAD

**Issue by ezeev** [gemworks/gem-farm-ui#17]
I have a farm that has a whitelist configured on it (using creator address) on devnet . No NFTs are showing on this UI under "Your wallet". 

This farm works fine with the wallet I'm testing with the gemworks.gg site. Am I missing a configuration step or something?

**Comment by eliagoris** [comment]
Thank you, @ezeev. I just did a revert. The last merge caused it.

Remember, if you want to filter NFTs by the creator on the frontend, you can pass an array of addresses [here](https://github.com/gemworks/gem-farm-ui/blob/main/hooks/useGemFarmStaking.ts#L17)
