### ISSUE TITLE
Error While Running on Local Host

### ISSUE THREAD

**Issue by izzyx6** [gemworks/gem-farm-ui#19]
Good day, I keep getting this error when I try to run the gem farm UI on my local on devnet

"Unhandled Runtime Error
Error: failed to get token accounts owned by account 51XTdE9XkAqSYoSNw5aqQq1AJg3DKjT6Sjt61PYY7GE7: Node detected it replayed bad version of slot 164160000 with id 1123473, thus the scan on said slot was aborted"

Please help. I have set my .env file with GEMFARM_ID and respectively network parameters.

**Comment by eliagoris** [comment]
Hey @izzyx6, this is an RPC problem; try refreshing, or changing the RPC on the `.env` file => `NEXT_PUBLIC_SOLANA_RPC_HOST` variable
