### ISSUE TITLE
Some files were "undone" in a merge, I noticed while going through the changes.

### ISSUE THREAD

**Issue by noseagenft** [gemworks/gem-farm-ui#20]
https://github.com/gemworks/gem-farm-ui/commit/d447526adb91e764c4047685d41e8e1782d7e252

@kubaplata @eliagoris

**Comment by eliagoris** [comment]
LFG https://github.com/gemworks/gem-farm-ui/commit/e2de95578ac440cd56722026a145fe27cb52048c

Thank you so much @noseagenft
