### ISSUE TITLE
What is the difference between GEMFARM_ID and GEM_FARM_PROG_ID?

### ISSUE THREAD

**Issue by AcornVoyager** [gemworks/gem-farm-ui#3]
Generally, what are these variables?

NEXT_PUBLIC_GEMFARM_ID
NEXT_PUBLIC_GEM_BANK_PROG_ID
NEXT_PUBLIC_GEM_FARM_PROG_ID

**Comment by eliagoris** [comment]
`NEXT_PUBLIC_GEMFARM_ID` is your farm ID when you create it through https://www.gemfarm.gg/

The other ones are not being used, so please ignore them. I will update the repo
