### ISSUE TITLE
Move more than one Gem at a time?

### ISSUE THREAD

**Issue by daddydonke** [gemworks/gem-farm-ui#4]
We are still struggling with moving more than one gem at a time, or adding gems once staking starts.  Is this a FE issue?

**Comment by eliagoris** [comment]
> We are still struggling with moving more than one gem at a time

Can you post a screenshot or something pointing to this problem? 

> adding gems once staking starts

This is expected behavior. Gem farm locks the vault once staking is active. Must unstake first
