### ISSUE TITLE
Filtering NFTs in wallet

### ISSUE THREAD

**Issue by Alsabbagh16** [gemworks/gem-farm-ui#7]
Is there a way to filter nfts in a wallet?
Making only a certain collection visible

**Comment by eliagoris** [comment]
Yes it's pretty easy actually, but I haven't got time to add it!

Here's a working example: https://github.com/magicshards/solana-web-app/blob/main/hooks/useWalletNFTs.tsx#L40

You would put it here: https://github.com/gemworks/gem-farm-ui/blob/main/hooks/useWalletNFTs.tsx#L34

**Comment by Alsabbagh16** [comment]
Thank you so much!

**Comment by eliagoris** [comment]
Added this on https://github.com/gemworks/gem-farm-ui/commit/83a387352a1583f0f4c45dd7b60d61cc08bbbf35

Only have to add an array of creator address to https://github.com/gemworks/gem-farm-ui/blob/main/hooks/useWalletNFTs.tsx#L33
